package mypack;
// Generated May 16, 2021 10:21:26 PM by Hibernate Tools 4.3.1



/**
 * Employees generated by hbm2java
 */
public class Employees  implements java.io.Serializable {


     private int id;
     private int age;
     private String first;
     private String last;

    public Employees() {
    }

	
    public Employees(int id, int age) {
        this.id = id;
        this.age = age;
    }
    public Employees(int id, int age, String first, String last) {
       this.id = id;
       this.age = age;
       this.first = first;
       this.last = last;
    }

    public Employees(String num, String age, String fname, String lname) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getAge() {
        return this.age;
    }
    
    public void setAge(int age) {
        this.age = age;
    }
    public String getFirst() {
        return this.first;
    }
    
    public void setFirst(String first) {
        this.first = first;
    }
    public String getLast() {
        return this.last;
    }
    
    public void setLast(String last) {
        this.last = last;
    }




}


